# Generated by Django 5.0.2 on 2024-02-11 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_rename_word_words'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='UserDict',
        ),
    ]
